## Lecture 3 (18 Oct 2025)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/kosavina/hse-python-2025/blob/main/Lecture_3.ipynb)

# Conditional Execution (Control Flow)

Conditional statements allow your program to execute certain pieces of code based on specific conditions.

| Precedence | Operator | Description | Associativity |
|------------|----------|-------------|---------------|
| 1 (Highest) | () | Parentheses | N/A |
| 2 | ** | Exponentiation | Right-to-left |
| 3 | +x, -x, ~x | Unary plus, unary minus, bitwise NOT | Right-to-left |
| 4 | *, /, //, % | Multiplication, division, floor division, modulo | Left-to-right |
| 5 | +, - | Addition, subtraction | Left-to-right |
| 6 | <<, >> | Bitwise left shift, right shift | Left-to-right |
| 7 | & | Bitwise AND | Left-to-right |
| 8 | ^ | Bitwise XOR | Left-to-right |
| 9 | \| | Bitwise OR | Left-to-right |
| 10 | in, not in, is, is not, <, <=, >, >=, !=, == | Comparison operators, membership, identity | Left-to-right |
| 11 | not | Logical NOT | Right-to-left |
| 12 | and | Logical AND | Left-to-right |
| 13 | or | Logical OR | Left-to-right |
| 14 | := | Walrus (assignment expression) | Right-to-left |
| 15 | if-else | Conditional expression (e.g., x if condition else y) | Right-to-left |
| 16 | lambda | Lambda expression | Right-to-left |
| 17 (Lowest) | = | Assignment (and augmented assignments like +=, -=, etc.) | Right-to-left |

## If Statements

The if statement is used to test a condition. If the condition is True, the indented block of code under the if statement gets executed.

In Python, several values evaluate to True when used in a conditional context. Here are some key cases:

1. Non-zero Numbers: Any integer or float that is not zero (1, -1, 3.14, etc.)
2. Non-empty Strings: Any string with at least one character ("Hello", " "), except the empty string ""
3. Non-empty Data Structures: Lists, dictionaries, tuples, and sets with at least one element ([1], {0: "value"}, ("a",), {1})
4. Custom Objects: Any instance of a class, unless it has a __bool__ or __len__ method that returns False or zero
5. True: The Boolean literal True itself
6. Non-None Values: Any object that isn’t explicitly None (such as instances of classes, functions, and other data types)

These values will make a conditional statement like if <value>: execute the block because they are truthy.

![image.png]()

```python
if condition:
    # Code to execute if condition is True
```

In [ ]:
age = 18

if age >= 18:
    print("You are eligible to vote.")

## Else Statements

The else statement can be used to execute code when the if condition is False.

```python
if condition:
    # Code if condition is True
else:
    # Code if condition is False
```

In [ ]:
age = 16

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

## Elif Statements

The elif (short for “else if”) statement allows you to check multiple conditions.

```python
if condition1:
    # Code if condition1 is True
elif condition2:
    # Code if condition2 is True
else:
    # Code if all conditions are False
```

In [ ]:
score = 85

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
else:
    print("Grade: C")

## Nested Conditions
You can have conditions within conditions.

In [ ]:
num = 10

if num > 0:
    print("Positive number")
    if num % 2 == 0:
        print("Even number")
    else:
        print("Odd number")
else:
    print("Negative number")

## The ternary conditional operator

```python
value_if_true if condition else value_if_false
```

In [ ]:
x = 10
result = "Positive" if x > 0 else "Non-positive"
print(result)

## Logical Operators

Logical operators allow you to combine multiple conditions.

* and: True if both conditions are True
* or: True if at least one condition is True
* not: Inverts the truth value

In [ ]:
age = 25
income = 50000

if age >= 18 and income >= 30000:
    print("You are eligible for a credit card.")

# Loops
Loops are used to execute a block of code repeatedly.

## While Loops

A while loop executes as long as a specified condition is True.

```python
while condition:
    # Code to execute repeatedly
```

In [ ]:
count = 1

while count <= 5:
    print("Count:", count)
    count += 1

## For Loops

A for loop is used for iterating over a sequence (like a list, tuple, dictionary, set, or string).

```python
for variable in sequence:
    # Code to execute repeatedly
```

In [ ]:
fruits = ["apple", "banana", "cherry"]

for i in fruits:
    print("I like", i)

## Using range() Function

In [ ]:
for i in range(5):
    print("Number:", i)

## Loop Control Statements

Control statements change the execution flow of loops.

### Break Statement

Exits the loop immediately.

In [ ]:
for i in range(1, 11):
    if i == 5:
        break
    print(i)

In [ ]:
%%timeit

for i in range(int(1.e+8)):
  break

In [ ]:
%%timeit

for i in list(range(int(1.e+8))):
  break

### Continue Statement

Skips the current iteration and continues with the next.

In [ ]:
for i in range(1, 6):
    if i == 3:
        continue
    print(i)

### Pass Statement

Does nothing; it acts as a placeholder.

In [ ]:
for i in range(5):
    pass  # To be implemented later

### else Clauses on Loops

In a for or while loop the break statement may be paired with an else clause. If the loop finishes without executing the break, the else clause executes.

In a for loop, the else clause is executed after the loop finishes its final iteration, that is, if no break occurred.

In a while loop, it’s executed after the loop’s condition becomes false.

In either kind of loop, the else clause is not executed if the loop was terminated by a break. Of course, other ways of ending the loop early, such as a return or a raised exception, will also skip execution of the else clause.

```python
numbers = [-3, -1, 4, -2, 6, 7, -5]

for num in numbers:
    if num < 0:  # Skip negative numbers
        print(f"Skipping {num} (negative)")
        continue
    if num % 2 == 0:  # Found a positive even number
        print(f"Found positive even number: {num}")
        break
    print(f"Checking {num} (not even)")
else:
    print("No positive even number found")
```

# map(), filter(), and reduce()

## Overview

* map(): Applies a function to every item of an iterable (e.g., list, tuple) and returns a map object (an iterator).
* filter(): Constructs an iterator from elements of an iterable for which a function returns true.
* reduce(): Applies a function of two arguments cumulatively to the items of an iterable, reducing the iterable to a single value.

## map() Function

The map() function allows you to apply a function to all the items in an input list or iterable.

```python
map(function, iterable)
```

* function: The function to apply to each item.
* iterable: The iterable whose items you want to process.

Returns a map object (which is an iterator) containing the results.

In [ ]:
def square(y):
    return y * y

numbers = [1, 2, 3, 4, 5]
squared_numbers = map(square, numbers)
print(squared_numbers)
print(list(squared_numbers))

In [ ]:
numbers = [1, 2, 3, 4, 5]
squared_numbers = map(lambda x: x * x, numbers)

print(list(squared_numbers))

You can pass multiple iterables to map() if the function accepts multiple arguments.

In [ ]:
numbers1 = [1, 2, 3]
numbers2 = [4, 5, 6]
sum_numbers = map(lambda x, y: x + y, numbers1, numbers2)

print(list(sum_numbers))

## filter() Function

The filter() function constructs an iterator from elements of an iterable for which a function returns True.

```python
filter(function, iterable)
```
* function: A function that returns a boolean value (True or False).
* iterable: The iterable to be filtered.

function: A function that returns a boolean value (True or False).
	•	iterable: The iterable to be filtered.

In [ ]:
def is_even(number):
    return number % 2 == 0

numbers = [1, 2, 3, 4, 5]
even_numbers = filter(is_even, numbers)

print(list(even_numbers))

In [ ]:
numbers = [1, 2, 3, 4, 5]
odd_numbers = filter(lambda x: x % 2 != 0, numbers)

print(list(odd_numbers))

## reduce() Function

The reduce() function applies a function of two arguments cumulatively to the items of an iterable, reducing the iterable to a single value.

```python
from functools import reduce
reduce(function, iterable[, initializer])
```

* function: A function of two arguments.
* iterable: The iterable to be reduced.
* initializer (optional): A value to start the accumulation.

Returns a single value.

In [ ]:
from functools import reduce

numbers = [1, 2, 3, 4, 5]
sum_numbers = reduce(lambda x, y: x + y, numbers)

print(sum_numbers)

In [ ]:
from functools import reduce

numbers = [5, 2, 8, 1, 9]
max_number = reduce(lambda x, y: x if x > y else y, numbers)

print(max_number)

## Combining map(), filter(), and reduce()

You can combine these functions to perform complex data processing tasks.

Example: Sum of Squares of Even Numbers

Let’s find the sum of the squares of even numbers in a list.

In [ ]:
from functools import reduce

numbers = [1, 2, 3, 4, 5, 6]

# Step 1: Filter even numbers
even_numbers = filter(lambda x: x % 2 == 0, numbers)
even_numbers = list(even_numbers)
print(even_numbers)

# Step 2: Square each even number
squared_even_numbers = map(lambda x: x * x, even_numbers)
# print(list(squared_even_numbers))

# Step 3: Sum the squared even numbers
sum_of_squares = reduce(lambda x, y: x + y, squared_even_numbers)
print(sum_of_squares)

# Comprehensions
Comprehensions in Python offer a concise way to create collections like lists, tuples, dictionaries, and sets by applying expressions to each item in an iterable. Here’s a breakdown of each type with examples:

## List Comprehension

A list comprehension generates a new list by transforming elements in an existing iterable, typically with a single line of code.

``` python
[expression for item in iterable if condition]
```

In [ ]:
numbers = [1, 2, 3, 4, 5]
squares = [x**2 for x in numbers]
# Output: [1, 4, 9, 16, 25]

In [ ]:
even_squares = [x**2 for x in numbers if x % 2 == 0]
# Output: [4, 16]
print(even_squares)

## Tuple Comprehension (using tuple() with generator expressions)

Python doesn’t have a dedicated tuple comprehension; instead, we use a generator expression inside the tuple() function to create a tuple.

``` python
tuple(expression for item in iterable if condition)
```

In [ ]:
numbers = [1, 2, 2, 3, 4, 4, 5]
squared_tuple = tuple(x**2 for x in numbers)
print(squared_tuple)
# Output: (1, 4, 9, 16, 25)

## Dictionary Comprehension

Dictionary comprehension is a way to construct dictionaries by specifying both keys and values.

``` python
{key_expression: value_expression for item in iterable if condition}
```

In [ ]:
words = ["apple", "banana", "cherry"]
word_lengths = {x: len(x) for x in words}
# Output: {'apple': 5, 'banana': 6, 'cherry': 6}
print(word_lengths)

In [ ]:
numbers = [1, 2, 2, 3, 4, 4, 5]
square_dict = {x: x**2 for x in numbers if x % 2 == 0}
print(square_dict)
# Output: {2: 4, 4: 16}

## Set Comprehension

A set comprehension generates a set by applying an expression to each item in an iterable. It follows the same syntax as list comprehension but uses curly braces {}.

``` python
{expression for item in iterable if condition}
```

In [ ]:
numbers = [1, 2, 2, 3, 4, 4, 5]
unique_squares = {x**2 for x in numbers}
# Output: {1, 4, 9, 16, 25}

In [ ]:
even_squares = {x**2 for x in numbers if x % 2 == 0}
# Output: {4, 16}

Summary

* List Comprehension:
``` python
[expression for item in iterable if condition]
```
* Tuple Comprehension:
``` python
tuple(expression for item in iterable if condition)
```
* Dictionary Comprehension:
``` python
{key_expression: value_expression for item in iterable if condition}
```
* Set Comprehension:
``` python
{expression for item in iterable if condition}
```

These comprehensions provide a clear, concise, and often more readable way to build collections in Python.

## Counter object

The Counter class in Python’s collections module is a specialized dictionary subclass for counting hashable objects. It’s ideal for tallying occurrences in iterables like lists, strings, or tuples.

In [ ]:
from collections import Counter

In [ ]:
items = ['apple', 'banana', 'apple', 'orange', 'banana']
counter = Counter(items)
print(counter)

In [ ]:
print(counter['apple'])
print(counter['grape'])

In [ ]:
counter.most_common(1)

In [ ]:
list(counter.elements())

In [ ]:
counter.update(items)

In [ ]:
print(counter)

# Exceptions

In Python, try...except...finally...else is a construct used to handle exceptions, execute cleanup actions, and specify code that should run only if no exceptions occur. Here’s a breakdown of how each part works together:

``` python
try:
    # Code that might raise an exception
except SomeException:
    # Code that runs if a specific exception occurs
else:
    # Code that runs only if no exceptions occur in the try block
finally:
    # Code that always runs, regardless of an exception
```

* **try** Block: The code in this block is executed first. If an exception occurs, the rest of the try block is skipped, and control is passed to the except block. If no exception occurs, control passes to the else block.
* **except** Block: This block catches and handles specific exceptions. If an exception matching the one specified in except is raised in the try block, the except block runs. If no exception occurs, except is skipped.
* **else** Block: The else block runs only if no exceptions are raised in the try block. This is useful for code that should only execute if the try block was successful.
* **finally** Block: The finally block always executes, regardless of whether an exception was raised or not. It’s often used for cleanup actions (e.g., closing files or network connections).

In [ ]:
def divide_numbers(a, b):
  return a / b

In [ ]:
divide_numbers(6, 0)

In [ ]:
def divide_numbers(a, b):
    try:
        result = a / b
    except:
        print("Error: Division by zero is not allowed.")
    else:
        print("Division successful. The result is:", result)
    finally:
        print("Execution of the finally block: Clean up resources if needed.")

In [ ]:
divide_numbers(10, 2)  # This should complete successfully and run the else block

In [ ]:
divide_numbers(10, 0)  # This  raise an exception and skip the else block